### ISSUE TITLE
cp: target '/usr/include/cdirip' is not a directory

### ISSUE THREAD

**Issue by RossComputerGuy** [jozip/cdirip#2]
You made a mistake in the `install` target.
```
cp: target '/usr/include/cdirip' is not a directory
make: *** [Makefile:38: install] Error 1
```

**Comment by jozip** [comment]
Nope. `Makefile` is apparently for rolling Debian packages. Use `Makefile.linux` to get yourself a binary.
(I didn't write this, I only threw it onto Github for posterity. I am accepting PRs, though, if you feel like hacking it.)
